myside3/blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^blog\/$', views.post_list, name='post_list'),
    url(r'^blog8a\/$', views.post_list8a, name='post_list8a'),
    url(r'^blog8b\/$', views.post_list8b, name='post_list8b'),
    url(r'^blog9c\/$', views.post_list9c, name='post_list9c'),
    url(r'^$', views.show_homepage, name='index'),
    url(r'^blog/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^login/$', views.login_user, name='log_in'),
    url(r'^blog/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^change_password/$', views.change_password, name='change_password'),
    url(r'^change_password_done/$', views.change_password_done, name='change_password_done'),
    url(r'^disclaimer/$', views.show_disclaimer, name='disclaimer'),

]

myside3/myside3/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
#from django.contrib import admin
#admin.autodiscover()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls), name='admin'),
#    url(r'', include('index.html')),
    url(r'', include('blog.urls')),
#    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myside3/blog/models.py
from django.db import models
from django.utils import timezone
from ckeditor.fields import RichTextField


class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    abstract = models.TextField(max_length=300)
    text = RichTextField()
    cdate = models.DateTimeField(default=timezone.now)
    pdate = models.DateTimeField(blank=True, null=True)
    mainpict = models.FileField(upload_to='uploads/', default='uploads/Pxjq6.jpg')
    atachement1 = models.FileField(upload_to='uploads/',blank=True, null=True)
    atachement2 = models.FileField(upload_to='uploads/',blank=True, null=True)
    atachement3 = models.FileField(upload_to='uploads/',blank=True, null=True)
    kurs = models.ForeignKey('auth.Group')

    def publish(self):
        self.pdate = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-pdate']

class Comment(models.Model):
    post = models.ForeignKey('blog.Post', related_name='comments')
    author = models.CharField(max_length=200)
    text = RichTextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

myside3/blog/forms.py
from django import forms
from ckeditor.fields import RichTextField
from .models import Comment


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

myside3/blog/views.py
#def homepage(request):
#    if request.user.is_anonymous():
#
#    else:

from django.utils import timezone
from .models import Post
from django.http import *
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, get_object_or_404
from .forms import CommentForm
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.models import Group

# Create your views here.
@user_passes_test(lambda u: Group.objects.get(name='EFGK2PH1617') in u.groups.all(), login_url='/login/')
#@login_required(login_url='/login/')
def post_list(request):
    posts = Post.objects.filter(kurs__name='EFGK2PH1617').filter(pdate__lte=timezone.now())#.order_by('published_date')
    return render(request, 'blog/post_list.html', {'posts': posts})

@user_passes_test(lambda u: Group.objects.get(name='8aPH1617') in u.groups.all(), login_url='/login/')
#@login_required(login_url='/login/')
def post_list8a(request):
    posts = Post.objects.filter(kurs__name='8aPH1617').filter(pdate__lte=timezone.now())#.order_by('published_date')
    return render(request, 'blog/post_list.html', {'posts': posts})

@user_passes_test(lambda u: Group.objects.get(name='8bPH1617') in u.groups.all(), login_url='/login/')
#@login_required(login_url='/login/')
def post_list8b(request):
    posts = Post.objects.filter(kurs__name='8bPH1617').filter(pdate__lte=timezone.now())#.order_by('published_date')
    return render(request, 'blog/post_list.html', {'posts': posts})

@user_passes_test(lambda u: Group.objects.get(name='9cM1617') in u.groups.all(), login_url='/login/')
#@login_required(login_url='/login/')
def post_list9c(request):
    posts = Post.objects.filter(kurs__name='9cM1617').filter(pdate__lte=timezone.now())#.order_by('published_date')
    return render(request, 'blog/post_list.html', {'posts': posts})

@login_required(login_url='/login/')
def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    u = request.user
    for g in u.groups.all():
        if g == post.kurs:
            return render(request, 'blog/post_detail.html', {'post': post})
    return render(request, 'blog/index.html')

def show_homepage(request):
    return render(request, 'blog/index.html')

def show_disclaimer(request):
    return render(request, 'blog/disclaimer.html')

def login_user(request):
    logout(request)
    username = password = ''
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect('/')
    return render(request, 'blog/login.html')

def change_password(request):
    password_old = password_new1 = password_new2 = ''
    if request.user.is_authenticated():
        if request.POST:
            password_old = request.POST['password_old']
            password_new1 = request.POST['password_new1']
            password_new2 = request.POST['password_new2']

            if request.user.check_password(password_old) and password_new1 == password_new2:
                request.user.set_password(password_new1)
                request.user.save()
                return render(request, 'blog/change_password_done.html')
            else:
                return render(request, 'blog/change_password.html')
        else:
            return render(request, 'blog/change_password.html')
    else:
        return render(request, 'blog/login.html')

def change_password_done(request):
    return render(request, 'blog/change_password_done.html')

@login_required(login_url='/login/')
def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/add_comment_to_post.html', {'form': form})

myside3/blog/templates/blog/add_comment_to_post.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="container mtb">
    <p class="row">
    <div class="col-lg-8">
        <h3>New comment</h3>
        <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
        </form>
    </div>
</div>
{% endblock %}

myside3/blog/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!--    <link rel="shortcut icon" href={% static 'img/pony.png' %}> -->

    <title>TILL LIEBER</title>

    <!-- Bootstrap core CSS -->
    <link href={% static 'css/bootstrap.css' %} rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href={% static 'css/style.css' %} rel="stylesheet">
    <link href={% static 'css/font-awesome.min.css' %} rel="stylesheet">

  </head>

  <body>

    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
	  <a class="navbar-brand" href="/">TILL LIEBER</a>
        </div>
        <div class="navbar-collapse collapse navbar-right">
          <ul class="nav navbar-nav">
          {%if user.is_authenticated %}
              <li><a href={% url 'blog:log_in' %}>LOG OUT!</a></li>
          {% else %}
             <li><a href={% url 'blog:log_in' %}>LOG IN!</a></li>
          {% endif %}
		  <li><a href={% url 'blog:post_list' %}>EFGK2PH</a></li>
		  <li><a href={% url 'blog:post_list8a' %}>8aPH</a></li>
		  <li><a href={% url 'blog:post_list8b' %}>8bPH</a></li>
		  <li><a href={% url 'blog:post_list9c' %}>9cM</a></li>
            <li class="dropdown active">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">MORE<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="blog.html">ABOUT ME</a></li>
                <li><a href="single-post.html">UBs</a></li>
                <li><a href={% url 'blog:disclaimer' %}>DISCLAIMER</a></li>
                <li><a href={% url 'blog:change_password'%}>Passwort ändern!</a></li>
                <li><a href={% url 'admin:index' %}>ADMIN</a></li>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

	 
	{% block content %}
	 	
	

			

	{% endblock %}
	<!-- *****************************************************************************************************************
	 FOOTER
	 ***************************************************************************************************************** -->
	 <div id="footerwrap">
	 	<div class="container">
		 	<div class="row">
		 		<div class="col-lg-4 col-lg-push-2">
		 			<h4>About</h4>
		 			<div class="hline-w"></div>
                    <p>
                        Die in den jeweiligen blogs verfassten Beiträge ersetzen in keiner Weise die im Unterricht zu
                        tätigen Mitschriften. Es sind nur grobe Zusammenfassungen oder vertiefende Informationen zu
                        den im Unterricht behandelten Themen
                    </p>
		 		</div>
		 		
				<div class="col-lg-4 col-lg-push-2">
		 			<h4>Kontakt/Disclaimer</h4>
		 			<div class="hline-w"></div>
                    <p>
                        <a href={% url 'blog:disclaimer' %}>DISCLAIMER</a><br>
                        {% load email_obfuscator %}
                        {{ 'lieber@hhgonline.de'|obfuscate_mailto }}

                    </p>
		 		</div>
		 	
		 	</div><!--/row -->
	 	</div><!--/container -->
	 </div><!--/footerwrap -->
	 
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src={% static 'js/bootstrap.min.js' %}></script>
    <script src={% static 'js/jquery.hoverdir.js' %}></script>
    <script src={% static 'js/jquery.hoverex.min.js' %}></script>
    <script src={% static 'js/jquery.prettyPhoto.js' %}></script>
    <script src={% static 'js/jquery.isotope.min.js' %}></script>
    <script src={% static 'js/custom.js' %}></script>
    <script src='https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML'></script>
    <script>
      $(document).ready(function() {

       var docHeight = $(window).height();
       var footerHeight = $('#footerwrap').outerHeight();
       var footerTop = $('#footerwrap').position().top + footerHeight;

       if (footerTop < docHeight) {
        $('#footerwrap').css('margin-top', (docHeight - footerTop) + 'px');
       }
      });
    </script>
  </body>
</html>

myside3/blog/templates/blog/change_password.html
{% extends 'blog/base.html' %}
{% block content %}

    <div class="container mtb">
		<div class="row">
			<div class="col-lg-8 col-lg-offset-2">
                <h3>
                    Bitte logge dich ein, damit du deinen Klassenblog sehen kannst.
                </h3>
                <form class="form-horizontal" name="ChangePWForm" action="/change_password/" method="post">
                {% csrf_token %}
                {% if next %}
                    <input type="hidden" name="next" value="{{ next }}" />
                {% endif %}
                <div class="control-group">
                    <label class="control-label" for="password">altes Passwort</label>
                    <div class="controls">
                        <input type="password" name="password_old" id="password" placeholder="Password old">
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="password">neues Passwort</label>
                    <div class="controls">
                        <input type="password" name="password_new1" id="password" placeholder="Password new">
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="password">neues Passwort wiederholen</label>
                    <div class="controls">
                        <input type="password" name="password_new2" id="password" placeholder="Password new">
                    </div>
                </div>
                <div class="control-group">
                    <div class="controls">
                        <button type="submit" class="save btn btn-default">Submit</button>
                    </div>
                </div>
                </form>

            </div>
         </div>
    </div>

{% endblock %}

myside3/blog/templates/blog/change_password_done.html
{% extends 'blog/base.html' %}
{% block content %}
    <div class="container mtb">
		<div class="row">
			<div class="col-lg-8 col-lg-offset-2">
                <h3>
                    Passwort wurde geändert.
                </h3>
            </div>
         </div>
    </div>
{% endblock %}

myside3/blog/templates/blog/disclaimer.html
{% extends 'blog/base.html' %}
{% block content %}

	<div class="container mtb" style="	margin-bottom: 10px">
		<div class="row" style="background: white">
			<!-- SIDEBAR -->
			<div class="col-lg-4 col-lg-push-8">
				<h4>Search</h4>
				<div class="hline"></div>
				<p>
					<br/>
					<input type="text" class="form-control" placeholder="funktioniert noch nicht...">
				</p>
				<!--		<div class="spacing"></div> -->

			</div>

	 <! -- BLOG POSTS LIST -->
			<div class="col-lg-8 col-lg-pull-4">
				<div class="panel panel-default">
					<div class="panel-footer">
                        <h1>Impressum</h1>
                        <h2>Angaben gemäß § 5 TMG:</h2>

                        <p>
                            Till Lieber<br>
                            Myliusstraße 7<br>
                            50823 Köln<br>
                        </p>

                        <h2>Kontakt:</h2>

                        {% load email_obfuscator %}
                        {{ 'lieber@hhgonline.de'|obfuscate_mailto }}

                        <h2>Verantwortlich für den Inhalt nach § 55 Abs. 2 RStV:</h2>

                        <p>
                            Till Lieber<br>
                            Myliusstraße 7<br>
                            50823 Köln<br>
                        </p>

                        <h1>Haftungsausschluss (Disclaimer)</h1>
                        <h2>Haftung für Inhalte</h2>
                        <p>
                            Als Diensteanbieter sind wir gemäß § 7 Abs.1 TMG für eigene Inhalte auf diesen Seiten nach den
                            allgemeinen Gesetzen verantwortlich. Nach §§ 8 bis 10 TMG sind wir als Diensteanbieter jedoch
                            nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach
                            Umständen zu forschen, die auf eine rechtswidrige Tätigkeit hinweisen. Verpflichtungen zur
                            Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben
                            hiervon unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis
                            einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden von entsprechenden
                            Rechtsverletzungen werden wir diese Inhalte umgehend entfernen.
                        </p>
                        <h2>Haftung für Links</h2>
                        <p>
                            Unser Angebot enthält Links zu externen Webseiten Dritter, auf deren Inhalte wir keinen
                            Einfluss haben. Deshalb können wir für diese fremden Inhalte auch keine Gewähr übernehmen.
                            Für die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten
                            verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf mögliche Rechtsverstöße
                            überprüft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar. Eine permanente
                            inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte einer
                            Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige
                            Links umgehend entfernen.
                        </p>
                        <h2>Urheberrecht</h2>
                        <p>
                            Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem
                            deutschen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der
                            Verwertung außerhalb der Grenzen des Urheberrechtes bedürfen der schriftlichen Zustimmung des
                            jeweiligen Autors bzw. Erstellers. Downloads und Kopien dieser Seite sind nur für den privaten,
                            nicht kommerziellen Gebrauch gestattet. Soweit die Inhalte auf dieser Seite nicht vom Betreiber
                            erstellt wurden, werden die Urheberrechte Dritter beachtet. Insbesondere werden Inhalte Dritter
                            als solche gekennzeichnet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam
                            werden, bitten wir um einen entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen
                            werden wir derartige Inhalte umgehend entfernen.
                        </p>
					</div>
				</div>
			</div><!--/col-lg-8 -->
		</div><!--/row -->
	</div><!--/container -->
{% endblock %}

myside3/blog/templates/blog/footer.html
	<!-- *****************************************************************************************************************
	 FOOTER
	 ***************************************************************************************************************** -->
	 <div id="footerwrap">
	 	<div class="container">
		 	<div class="row">
		 		<div class="col-lg-4">
		 			<h4>About</h4>
		 			<div class="hline-w"></div>
		 			<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.</p>
		 		</div>
		 		<div class="col-lg-4">
		 			<h4>Social Links</h4>
		 			<div class="hline-w"></div>
		 			<p>
		 				<a href="#"><i class="fa fa-dribbble"></i></a>
		 				<a href="#"><i class="fa fa-facebook"></i></a>
		 				<a href="#"><i class="fa fa-twitter"></i></a>
		 				<a href="#"><i class="fa fa-instagram"></i></a>
		 				<a href="#"><i class="fa fa-tumblr"></i></a>
		 			</p>
		 		</div>
		 		<div class="col-lg-4">
		 			<h4>Our Bunker</h4>
		 			<div class="hline-w"></div>
		 			<p>
		 				Some Ave, 987,<br/>
		 				23890, New York,<br/>
		 				United States.<br/>
		 			</p>
		 		</div>
		 	
		 	</div><! --/row -->
	 	</div><! --/container -->
	 </div><! --/footerwrap -->
	 
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src={% static 'js/bootstrap.min.js' %}></script>
    <script src={% static 'js/retina-1.1.0.js' %}></script>
    <script src={% static 'js/jquery.hoverdir.js' %}></script>
    <script src={% static 'js/jquery.hoverex.min.js' %}></script>
    <script src={% static 'js/jquery.prettyPhoto.js' %}></script>
    <script src={% static 'js/jquery.isotope.min.js' %}></script>
    <script src={% static 'js/custom.js' %}></script>
    <script src='https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML'></script>


  </body>
</html>

myside3/blog/templates/blog/header.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="assets/ico/favicon.ico">

    <title>TILL LIEBER</title>

    <!-- Bootstrap core CSS -->
    <link href={% static 'css/bootstrap.css' %} rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href={% static 'css/style.css' %} rel="stylesheet">
    <link href={% static 'css/font-awesome.min.css' %} rel="stylesheet">


    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    
    <script src={% static 'js/modernizr.js' %}></script>
  </head>

myside3/blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block content %}
<div id="headerwrap">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 col-lg-offset-2">
				<h3>Willkommen auf meiner Homepage {{ user.username }}!</h3>
				<h1>Der Unterrichtsblog zum nachlesen</h1>
				<h5>Auf dieser Seite wird zusätzliches Unterrichtsmaterial veröffentlicht. Um dieses einsehen zu können ist es erforderlich, dass man einen aktiven, für den speziellen Kurs freigeschalteten Benutzeraccount besitzt. Dieser wurde im Unterricht verteilt, sollten die Zugangsdaten vergessen worden sein, muss dies im Unterricht mitgeteilt werden.</h5>
			</div>
			<!--<div class="col-lg-8 col-lg-offset-2 img">-->
				<!--<img src="assets/img/browser.png" class="img-responsive">-->
			<!--</div>-->
		</div><!-- /row -->
    </div> <!-- /container -->
</div><!-- /headerwrap -->
{% endblock %}

myside3/blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% block content %}

    <div class="container mtb">
		<div class="row">
			<div class="col-lg-8 col-lg-offset-2">
                <div class="panel panel-default">
					<div class="panel-footer">
                        <h3>
                            Bitte logge dich ein, damit du deinen Klassenblog sehen kannst.
                        </h3>
                        <form class="form-horizontal" name="LoginForm" action="/login/" method="post">
                        {% csrf_token %}
                        {% if next %}
                            <input type="hidden" name="next" value="{{ next }}" />
                        {% endif %}
                        <div class="control-group">
                            <label class="control-label" for="username">Username</label>
                            <div class="controls">
                                <input type="text" id="username" name="username"  placeholder="Username">
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="password">Password</label>
                            <div class="controls">
                                <input type="password" name="password" id="password" placeholder="Password">
                            </div>
                        </div>
                        <div class="control-group">
                            <div class="controls">
                                <button type="submit" class="save btn btn-default">Login</button>
                            </div>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
         </div>
    </div>

{% endblock %}

myside3/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% block content %}

	 <div class="container mtb" style="	margin-bottom: 10px">
		<div class="row" style="background: white">
			<!-- SIDEBAR -->
			<div class="col-lg-4 col-lg-push-8">
				<h4>Search</h4>
				<div class="hline"></div>
				<p>
					<br/>
					<input type="text" class="form-control" placeholder="funktioniert noch nicht...">
				</p>
				<!--		<div class="spacing"></div> -->
			</div>

	 <! -- BLOG POSTS LIST -->
			<div class="col-lg-8 col-lg-pull-4" style=" margin-top: 20px">
				{% for post in posts %}
				<div class="panel panel-default">
					<div class="panel-footer">
						<p><img class="img-rounded" display: block max-width: 100% height: auto  src={{ post.mainpict.url }}></p>
						<a href={% url 'blog:post_detail' pk=post.pk %}><h3 class="ctitle">{{ post.title }}</h3></a>
						<p><csmall>{{ post.pdate }}</csmall> | <csmall>{{ post.author }}</csmall> | <csmall2>Comments: {{ post.comments.count }}</csmall2></p>
						<p>{{ post.abstract|safe }}</p>
						<p><a href={% url 'blog:post_detail' pk=post.pk %}>[Read More]</a></p>
						<!--<div class="hline"></div>-->
						<!--<div class="spacing"></div>-->
					</div>
				</div>
				{% endfor %}
			</div><!--/col-lg-8 -->
	 	</div><!--/row -->
	 </div><!--/container -->
{% endblock %}

myside3/blog/templates/blog/post_list1.html
<html>
	<head>
		<title>Django Girls blog</title>
	</head>
	<body>
		<div>
			<h1><a href="">Django Girls Blog</a></h1>
		</div>
		{% for post in posts %}
			<div>
				<p>published: {{ post.published_date }}</p>
				<h1><a href="">{{ post.title }}</a></h1>
				<p>{{ post.text|linebreaksbr }}</p>
			</div>
		{% endfor %}
	</body>
</html>